# Generated by Django 5.1.3 on 2024-12-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_description_remove_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Material',
            field=models.CharField(default='default', max_length=2000),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='default', max_length=2000),
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.CharField(default='default', max_length=2000),
        ),
        migrations.AddField(
            model_name='product',
            name='subName',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(default='default', max_length=2000),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.CharField(default='default', max_length=2000),
        ),
        migrations.AddField(
            model_name='product',
            name='yearOfManufacture',
            field=models.CharField(default='default', max_length=2000),
        ),
    ]
