# Generated by Django 5.1.2 on 2024-11-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('ended', 'Ended')], default='active', max_length=10),
        ),
    ]
