# Generated by Django 5.1.2 on 2024-11-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('ended', 'Ended'), ('sold', 'Sold'), ('locked', 'Locked')], default='active', max_length=10),
        ),
    ]
