# Generated by Django 5.1.2 on 2024-11-17 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auctions', '0002_auction_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bidding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bidding_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ending_time', models.DateTimeField()),
                ('auction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.auction')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biddings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
