# Generated by Django 5.1.2 on 2024-11-17 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0002_soldauction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soldauction',
            name='sold_at',
        ),
    ]
