# Generated by Django 5.1.2 on 2024-11-18 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0003_remove_soldauction_sold_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soldauction',
            old_name='auction',
            new_name='auction_id',
        ),
        migrations.RenameField(
            model_name='soldauction',
            old_name='user',
            new_name='user_id',
        ),
    ]
