# Generated by Django 5.1.2 on 2024-11-18 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0004_rename_auction_soldauction_auction_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soldauction',
            old_name='auction_id',
            new_name='auction',
        ),
        migrations.RenameField(
            model_name='soldauction',
            old_name='user_id',
            new_name='user',
        ),
    ]
