# Generated by Django 5.1.2 on 2024-11-18 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0005_rename_auction_id_soldauction_auction_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SoldAuction',
        ),
    ]
