# Generated by Django 5.1.2 on 2024-11-20 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0008_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='auction_id',
            new_name='auction',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_id',
        ),
    ]
